# Generated by Django 3.0.7 on 2020-06-11 18:41

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import tournamentPortalApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_dummy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_deadline', models.DateTimeField()),
                ('entry_limit', models.PositiveSmallIntegerField()),
                ('event_date', models.DateTimeField()),
                ('organiser_name', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[('net', 'Network'), ('loc', 'Physical location')], max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('game_format', models.CharField(choices=[('std', 'Standard'), ('wld', 'Wild')], max_length=3)),
                ('deck_format', models.CharField(choices=[('sin', 'Single-deck'), ('mul', 'Multiple-deck')], max_length=3)),
                ('description', models.TextField()),
                ('prizes', models.TextField()),
                ('creator', models.ForeignKey(on_delete=models.SET(tournamentPortalApp.models.getUserDeleted), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to=tournamentPortalApp.models.get_sponsor_file_path)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentPortalApp.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournamentPortalApp.Tournament')),
                ('user', models.OneToOneField(on_delete=models.SET(tournamentPortalApp.models.getUserDeleted), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
