# Generated by Django 3.0.6 on 2020-05-30 00:13

from django.conf import settings
from django.db import migrations, models
import tournamentPortalApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('entry_limit', models.PositiveSmallIntegerField()),
                ('event_date', models.DateTimeField()),
                ('organiser_name', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[], max_length=3)),
                ('location', models.CharField(max_length=50)),
                ('game_format', models.CharField(choices=[], max_length=3)),
                ('deck_format', models.CharField(choices=[], max_length=3)),
                ('creator', models.OneToOneField(on_delete=models.SET(tournamentPortalApp.models.getUserDeleted), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
